"""
    Haystack-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.feedback_api import FeedbackApi  # noqa: E501


class TestFeedbackApi(unittest.TestCase):
    """FeedbackApi unit test stubs"""

    def setUp(self):
        self.api = FeedbackApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_export_feedback(self):
        """Test case for export_feedback

        Export Extractive Qa Feedback  # noqa: E501
        """
        pass

    def test_get_feedback(self):
        """Test case for get_feedback

        User Feedback  # noqa: E501
        """
        pass

    def test_get_feedback_metrics(self):
        """Test case for get_feedback_metrics

        Eval Extractive Qa Feedback  # noqa: E501
        """
        pass

    def test_post_feedback(self):
        """Test case for post_feedback

        User Feedback  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
