"""
    Haystack-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.filter_request import FilterRequest


class TestFilterRequest(unittest.TestCase):
    """FilterRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterRequest(self):
        """Test FilterRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilterRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
