"""
    Haystack-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.document_api import DocumentApi  # noqa: E501


class TestDocumentApi(unittest.TestCase):
    """DocumentApi unit test stubs"""

    def setUp(self):
        self.api = DocumentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_documents(self):
        """Test case for delete_documents

        Delete Documents By Filter  # noqa: E501
        """
        pass

    def test_get_documents(self):
        """Test case for get_documents

        Get Documents By Filter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
