"""
    Haystack-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.file_upload_api import FileUploadApi  # noqa: E501


class TestFileUploadApi(unittest.TestCase):
    """FileUploadApi unit test stubs"""

    def setUp(self):
        self.api = FileUploadApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_file_upload_file_upload_post(self):
        """Test case for file_upload_file_upload_post

        File Upload  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
