"""
    Haystack-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.search_api import SearchApi  # noqa: E501


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_initialized_initialized_get(self):
        """Test case for initialized_initialized_get

        Initialized  # noqa: E501
        """
        pass

    def test_query_query_post(self):
        """Test case for query_query_post

        Query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
