"""
    Haystack-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.answer_serialized import AnswerSerialized
from openapi_client.model.document_serialized import DocumentSerialized
globals()['AnswerSerialized'] = AnswerSerialized
globals()['DocumentSerialized'] = DocumentSerialized
from openapi_client.model.label_serialized import LabelSerialized


class TestLabelSerialized(unittest.TestCase):
    """LabelSerialized unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelSerialized(self):
        """Test LabelSerialized"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LabelSerialized()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
