"""
    Haystack-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.document_serialized import DocumentSerialized


class TestDocumentSerialized(unittest.TestCase):
    """DocumentSerialized unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentSerialized(self):
        """Test DocumentSerialized"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocumentSerialized()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
