"""
    Haystack-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.feedback_api import FeedbackApi  # noqa: E501


class TestFeedbackApi(unittest.TestCase):
    """FeedbackApi unit test stubs"""

    def setUp(self):
        self.api = FeedbackApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_eval_extractive_qa_feedback_eval_feedback_post(self):
        """Test case for eval_extractive_qa_feedback_eval_feedback_post

        Eval Extractive Qa Feedback  # noqa: E501
        """
        pass

    def test_export_extractive_qa_feedback_export_feedback_get(self):
        """Test case for export_extractive_qa_feedback_export_feedback_get

        Export Extractive Qa Feedback  # noqa: E501
        """
        pass

    def test_user_feedback_feedback_get(self):
        """Test case for user_feedback_feedback_get

        User Feedback  # noqa: E501
        """
        pass

    def test_user_feedback_feedback_post(self):
        """Test case for user_feedback_feedback_post

        User Feedback  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
